version: '3'

networks:
  netbot:
    ipam:
      driver: default
      config:
        - subnet: 11.0.0.0/24

services:

  telegram-bot:
      networks:
        netbot:
          ipv4_address: 11.0.0.3
      build:
        context: ./bot
        dockerfile: Dockerfile
      restart: on-failure:10
      environment:
        TOKEN: $TOKEN
        RM_HOST: $RM_HOST
        RM_PORT: $RM_PORT
        RM_USER: $RM_USER
        RM_PASSWORD: $RM_PASSWORD
      env_file:
        - .env
      depends_on:
        - db
      volumes:
        - postgres-logs:/var/log/postgres

  db:
    networks:
      netbot:
        ipv4_address: 11.0.0.5
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_REPLICATION_USER: ${DB_REPL_USER}
      POSTGRES_REPLICATION_PASSWORD: ${DB_REPL_PASSWORD}
      POSTGRES_LOG_DESTINATION: stderr
      POSTGRES_LOGGING_COLLECTOR: on
      POSTGRES_LOG_FILENAME: postgresql.log
    user: ${DB_USER}
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    command: -c 'config_file=/var/lib/postgresql/data/postgresql.conf' -c 'hba_file=/var/lib/postgresql/data/pg_hba.conf' -c 'log_destination=stderr' -c 'logging_collector=on' -c 'log_directory=/var/log/postgres' -c 'log_filename=postgresql.log'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgres
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh

  repl_db:
    networks:
      netbot:
        ipv4_address: 11.0.0.6
    build:
      context: ./db_repl
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_REPLICATION_USER: ${DB_REPL_USER}
      POSTGRES_REPLICATION_PASSWORD: ${DB_REPL_PASSWORD}
    env_file:
      - .env
    ports:
      - "${DB_REPL_PORT}:5432"
    command: -c 'hot_standby=on' -c 'config_file=/var/lib/postgresql/data/postgresql.conf' -c 'hba_file=/var/lib/postgresql/data/pg_hba.conf'
    volumes:
      - pgrepldata:/var/lib/postgresql/data
      - ./db_repl/init.sh:/docker-entrypoint-initdb.d/init.sh

volumes:
  pgdata:
  pgrepldata:
  postgres-logs:
